insert into public.puzzles (
  id,
  date,
  puzzle_number,
  status,
  is_test,
  counts_toward_puzzle_number,
  song_title_english,
  song_title_korean,
  artist_name,
  album_art_url,
  source,
  source_track_id,
  source_country,
  preview_url,
  preview_start_seconds,
  canonical_answer_english,
  canonical_answer_korean,
  accepted_answers,
  difficulty,
  tags,
  notes
) values (
  '00000000-0000-4000-8000-000000000001',
  '2026-05-07',
  1,
  'published',
  false,
  true,
  'LOVE DIVE',
  '러브 다이브',
  'IVE',
  null,
  'manual',
  null,
  null,
  '/audio/popped-demo-preview.wav',
  8.4,
  'LOVE DIVE',
  '러브 다이브',
  array['LOVE DIVE', 'lovedive', '러브 다이브', '러브다이브'],
  'easy',
  array['demo'],
  'Local development seed for testing the public game and launch numbering.'
)
on conflict (id) do update set
  date = excluded.date,
  puzzle_number = excluded.puzzle_number,
  status = excluded.status,
  is_test = excluded.is_test,
  counts_toward_puzzle_number = excluded.counts_toward_puzzle_number,
  song_title_english = excluded.song_title_english,
  song_title_korean = excluded.song_title_korean,
  artist_name = excluded.artist_name,
  album_art_url = excluded.album_art_url,
  source = excluded.source,
  source_track_id = excluded.source_track_id,
  source_country = excluded.source_country,
  preview_url = excluded.preview_url,
  preview_start_seconds = excluded.preview_start_seconds,
  canonical_answer_english = excluded.canonical_answer_english,
  canonical_answer_korean = excluded.canonical_answer_korean,
  accepted_answers = excluded.accepted_answers,
  difficulty = excluded.difficulty,
  tags = excluded.tags,
  notes = excluded.notes;
